name: build and deploy

on:
  push:
    branches: ['main']

jobs:
  ci:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Run all checks
        run: pnpm run ci

  publish:
    name: publish packages
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v6
        with:
          run_install: true

      - run: pnpm run publishNpmPkg
        name: Publish npm packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
